build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12
  armhf: ghcr.io/home-assistant/armhf-base-python:3.12
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12
  i386: ghcr.io/home-assistant/i386-base-python:3.12
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Music League Bot"
  org.opencontainers.image.description: "Run Discord music competitions with submissions, voting, and leaderboards"
  org.opencontainers.image.source: "https://github.com/yourusername/musicleague-bot"
  org.opencontainers.image.licenses: "MIT"
