name: "Erin's Music League Bot"
version: "1.0.0"
slug: "musicleague_bot"
description: "A Discord bot for running music leagues with submissions, voting, and leaderboards"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
map:
  - share:rw
  - config:rw
  - addon_config:rw
options:
  discord_token: ""
  prefix: "!"
  submission_days: 3
  voting_days: 3
schema:
  discord_token: str
  prefix: str
  submission_days: "int(1,14)"
  voting_days: "int(1,14)"
